export const APP_INCREMENT_APISTACK = "APP_INCREMENT_APISTACK";
export const APP_DECREMENT_APISTACK = "APP_DECREMENT_APISTACK";

export const AUTH_SET_ACCESS_TOKEN = "AUTH_SET_ACCESS_TOKEN";
export const AUTH_SET_REFRESH_TOKEN = "AUTH_SET_REFRESH_TOKEN";
export const AUTH_SET_GOOGLE_TOKEN = "AUTH_SET_GOOGLE_TOKEN";